version: '3.6'

services:
  postgres:
    image: postgres:${POSTGRES_VER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pleroma

  web:
    build:
      context: ./pleroma-otp
      args:
        PLEROMA_VER: ${PLEROMA_VER}
    image: pleroma:${PLEROMA_VER}-otp
    volumes:
      - pleroma-uploads:/pleroma/uploads
      - ./config/prod.otp.exs:/etc/pleroma/config.exs
      - ./config/keys.otp.exs:/etc/pleroma/prod.secret.exs
    depends_on:
      - postgres
    networks:
      - pleroma
    healthcheck:
      start_period: 30s
    ports:
      - 4000:4000

  adminer:
    image: adminer
    networks:
      - pleroma
    ports:
      - 8080:8080

volumes:
  postgres-data:
    driver: local
  pleroma-uploads:
    driver: local

networks:
  pleroma:
    driver: bridge
